version: '2'
services:
  ipfs:
    image: brainstorm/ipfs-cluster:latest
    volumes: 
      - ./data:/data/ipfs
    ports:
      - "8080:8080"
      - "4001:4001"

  cgtd:
    image: ga4gh/cgtd
    environment:
      DOMAIN:
    ports:
      - "5000:5000"
    links:
      - ipfs
