apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    service: cgtd
  name: cgtd
spec:
  strategy:
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: cgtd
    spec:
      containers:
      - image: ga4gh/cgtd
        name: cgtd-0
        ports:
        - containerPort: 5000
          name: port-5000
        resources: {}
status: {}
