apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: cgtd
  name: cgtd
spec:
  ports:
  - name: port-5000
    port: 5000
    targetPort: 5000
  externalIPs:
    - 52.64.16.69
  selector:
    service: cgtd
  type: LoadBalancer
status:
  loadBalancer: {}
