language: python
branches:
  - master
  - no_init_bad_port
python:
  - '2.7'
install:
  # the new pep8 == pycodestyle
  - pip install pycodestyle
  - pip install flake8
script:
  - pycodestyle .
#  - flake8 .
