version: '2'
services:
  cgtd:
    build: .
    links:
     - ipfs
    ports:
     - "5001:5001"
  ipfs:
    image: ipfs/go-ipfs:latest
    ports:
      - "8080:8080"
      - "4001:4001"
      - "4002:4002/udp"
