version: '2'
services:
  cgtd:
    image: robcurrie/cgtd:latest
    links:
     - ipfs
    ports:
     - "5000:5000"
  ipfs:
    image: ipfs/go-ipfs:latest
    ports:
      - "8080:8080"
      - "4001:4001"
      - "4002:4002/udp"
